from django.conf.urls import include, url
from django.urls import path
from board.views import (
    disp_profiles,
    about,
    canvas,
    BoardCreateView,
    BoardDetailView,
    ImportBoardFormView,
    BoardDeleteView,
    UserBoardsView,
    save_canvas,
    use_invite,
    gen_invite,
    del_invite,
    kick_user,
    disp_board_settings,
    dispBoard,
    disp_classes,
    ClassRoomCreateView,
    createBoardForClassroom,
    use_invite_classroom,
    gen_classroom_invite,
    classroom_settings,
    kick_user_from_class)

urlpatterns = [
    url('profile/', UserBoardsView.as_view(), name='disp_profile'),
    url('about/', about, name='about'),
    url('canvas/', canvas, name='canvas'),
    url('classrooms/new/', ClassRoomCreateView.as_view(), name="create_classroom"),
    path('classrooms/newBoard/<int:pk>', createBoardForClassroom, name="add_classroom_board"),
    path('classrooms/generate/<int:pk>', gen_classroom_invite, name="gen_class_invite"),
    path('classrooms/settings/<int:pk>', classroom_settings, name="class_settings"),
    path('classrooms/join/<str:g_code>', use_invite_classroom, name='join_class'),
    path('classrooms/kick/<int:c_pk>', kick_user_from_class, name='kick_class'),
    url('classrooms/join/', use_invite_classroom, name="join_class_code"),
    url('classrooms/', disp_classes, name="disp_classrooms"),
    url('board/new/', BoardCreateView.as_view(), name='board-create'),
    url('board/import/', ImportBoardFormView.as_view(), name='board-import'),
    path('board/<int:pk>/', dispBoard, name='board-detail'),
    url('board/update/', save_canvas, name='save_canvas'),
    url(r'^board/join/$', use_invite, name='join'),
    path('board/join/<str:g_code>', use_invite, name='join_get'),
    path('board/<int:pk>/geninvite', gen_invite, name='gen_invite'),
    path('board/<int:pk>/delinvite', del_invite, name='del_invites'),
    path('board/<int:pk>/settings', disp_board_settings, name='board_settings'),
    path('board/<int:b_pk>/kick', kick_user, name='kick_user'),
    path('board/<int:pk>/delete/', BoardDeleteView.as_view(), name='board-delete'),
    url('board/update/', save_canvas, name='save_canvas'),
    url('', UserBoardsView.as_view(), name='disp-boards'),
]
