# Generated by Django 3.2 on 2021-04-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
